swagger: '2.0'
info:
  version: "1.0"
  title: 'Merchant Marketplace Subscription Requested Pusher'
  description: 'Merchant Marketplace Subscription Requested Pusher'

host: IMN.MER.SubsRQ.Pusher
basePath: /MerchantMarketplaceSubscriptionRequestedPusher

x-beezup-ops:
  codeGenType: actor
  repo: IMN
  appRoot: IMN.MER.SubsRQ.Pusher
  apiName: MerchantMarketplaceSubscriptionRequestedPusher
  namespace: IMN.MER.SubsRQ.Pusher
  comment: |
    Actor

paths:

  '/subscriptionsRequested':
    post:
      summary: Call the MerchantActor to handle the marketplace subscriptions requested
      parameters: 
      - name: request
        in: body
        required: true
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/externalMerchantMarketplaceSubscriptionsRequested'
      responses:
        204:
          description: Subscriptions's request have been pushed to the MerchantActor
          
definitions: {}