swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN - Merchant Offer Distributor For Exportation'

host: IMN.Offer.DIST.EXP
basePath: /OfferDistributorForExport

x-beezup-ops:
  codeGenType: eventHandlerActor
  repo: IMN
  product: IMN-CORE
  group: offer
  appRoot: IMN.Offer.DIST.EXP
  apiName: OfferDistributorForExport
  namespace: IMN.Offer.DIST.EXP
  applicationShortName: Order.Actors
  comment: |
    Actor
  using:
  - IMN.Offer.Events

paths:

  '/merchantOfferReceived':
    post:
      summary: When the merchant offer is Received
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferReceived'
      responses:
        204:
          description: OK
  
  

  '/merchantOfferDeleted':
    post:
      summary: When the merchant offer is deleted
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferDeleted'
      responses:
        204:
          description: OK


      
definitions: {}