swagger: '2.0'
info:
  version: "1.0"
  title: IMN ADAPTER - Offer Importation - Merchant's Message Router

host: IMN.ADPT.OfferIMP.Routers
basePath: /OfferImportationMerchantMessageRouter

x-beezup-ops:
  codeGenType: actor
  repo: IMN
  namespace: IMN.ADPT.OfferIMP.MER.Routers
  comment: |
    Actor 

paths:



  '/offerImportationEnabled':
    post:
      summary: When the offer importation is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferImportationEnabled'
      responses:
        204:
          description: OK


  '/offerImportationDisabled':
    post:
      summary: When the offer importation is disabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferImportationDisabled'
      responses:
        204:
          description: OK




definitions: {}