swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN - Merchant Marketplace Distributor for Exportation'

host: IMN.MER.MKP.DIST.EXP
basePath: /MerchantMarketplaceDistributorForExport

x-beezup-ops:
  codeGenType: eventHandlerActor
  repo: IMN
  appRoot: IMN.MER.MKP.DIST.EXP
  apiName: MerchantMarketplaceDistributorForExport
  namespace: IMN.MER.MKP.DIST.EXP
  comment: |
    Actor
  using:
  - IMN.MER.Events

paths:



  '/offerPublicationEnabled':
    post:
      summary: When the offer publication is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferPublicationEnabled'
      responses:
        204:
          description: OK


  '/offerPublicationDisabled':
    post:
      summary: When the offer publication is disabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferPublicationDisabled'
      responses:
        204:
          description: OK


  
  

  '/merchantMarketplacePricingSettingConfigured':
    post:
      summary: When the merchant configured the pricing of a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplacePricingSettingConfigured'
      responses:
        204:
          description: OK

      

      
definitions: {}