swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN - Merchant Offer Projector CosmosDb'

host: IMN.Offer.PROJ.CosmosDb
basePath: /OfferProjectionCosmosDb

x-beezup-ops:
  codeGenType: eventHandlerActor
  repo: IMN
  appRoot: IMN.Offer.PROJ.CosmosDb
  apiName: OfferProjectionCosmosDb
  namespace: IMN.Offer.PROJ.CosmosDb
  comment: |
    Actor
  using:
  - IMN.MER.Events
  - IMN.Offer.Events

paths:

  '/merchantOfferReceived':
    post:
      summary: When the merchant offer is Received
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferReceived'
      responses:
        204:
          description: OK
  

  '/merchantOfferDeleted':
    post:
      summary: When the merchant offer is deleted
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferDeleted'
      responses:
        204:
          description: OK


      
definitions: {}