swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN ADAPTER - Offer Importation Execution Message Router'
  
basePath: /OfferImportationExecutionMessageRouter
  
x-beezup-ops:
  repo: IMN
  appRoot: .
  namespace: IMN.ADPT.OfferIMPExecution.Routers
  comment: |
    Actor 
  
paths:




  '/completed':
    post:
      summary: When the offer importation is complted
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_importation-events/1.0#/definitions/offerImportationCompleted'
      responses:
        204:
          description: OK



definitions: {}