swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN - Merchant Projector Database'

host: IMN.MER.PROJ.Db
basePath: /MerchantProjectionApplier

x-beezup-ops:
  codeGenType: eventHandlerActor
  repo: IMN
  appRoot: IMN.MER.PROJ.Db
  apiName: MerchantProjectionApplier
  namespace: IMN.MER.PROJ.Db
  applicationShortName: MER.PROJ.Db
  comment: |
    Actor
  using:
  - IMN.MER.Events

paths:

  '/merchantCreated':
    post:
      summary: When the merchant is created
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantCreated'
      responses:
        204:
          description: OK
  
  '/merchantAcountInfoUpdated':
    post:
      summary: When the merchant updates his information
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantAcountInfoUpdated'
      responses:
        204:
          description: OK

  '/merchantMarketplaceCredentialConfigured':
    post:
      summary: When the merchant declared his marketplace credential
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceCredentialConfigured'
      responses:
        204:
          description: OK

  '/offerImportationEnabled':
    post:
      summary: When the offer importation is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferImportationEnabled'
      responses:
        204:
          description: OK


  '/offerImportationDisabled':
    post:
      summary: When the offer importation is disabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferImportationDisabled'
      responses:
        204:
          description: OK


  '/offerPublicationEnabled':
    post:
      summary: When the offer publication is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferPublicationEnabled'
      responses:
        204:
          description: OK


  '/offerPublicationDisabled':
    post:
      summary: When the offer publication is disabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferPublicationDisabled'
      responses:
        204:
          description: OK


  '/orderImportationEnabled':
    post:
      summary: When the order importation is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOrderImportationEnabled'
      responses:
        204:
          description: OK


  '/orderImportationDisabled':
    post:
      summary: When the offer importation is disabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOrderImportationDisabled'
      responses:
        204:
          description: OK

  '/merchantMarketplaceSubscriptionRequested':
    post:
      summary: When the subscription to the marketplace is requested by merchant 
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceSubscriptionRequested'
      responses:
        204:
          description: OK
          
  '/merchantMarketplaceSubscriptionAccepted':
    post:
      summary: When the merchant subscription is accepted by marketplace 
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceSubscriptionAccepted'
      responses:
        204:
          description: OK
          
  '/merchantMarketplaceSubscriptionRefused':
    post:
      summary: When the merchant subscription is refused by marketplace 
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceSubscriptionRefused'
      responses:
        204:
          description: OK
          
  '/merchantMarketplaceSubscriptionBlocked':
    post:
      summary: When the merchant subscription is blocked by marketplace 
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceSubscriptionBlocked'
      responses:
        204:
          description: OK

  '/merchantMarketplacePricingSettingConfigured':
    post:
      summary: When the merchant configured the pricing of a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplacePricingSettingConfigured'
      responses:
        204:
          description: OK
  
  '/merchantMarketplaceShippingPreprationSettingConfigured':
    post:
      summary: When the merchant configured the shipping preparation of a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceShippingPreprationSettingConfigured'
      responses:
        204:
          description: OK


  '/merchantMarketplaceShippingDeliverySettingConfigured':
    post:
      summary: When the merchant configure the delivery setting of a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceShippingDeliverySettingConfigured'
      responses:
        204:
          description: OK
  
    
  '/merchantMarketplaceShippingDeliverySettingDeleted':
    post:
      summary: When the merchant delete the delivery setting of a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceShippingDeliverySettingDeleted'
      responses:
        204:
          description: OK
  
  
  
  '/merchantOffersSourceMarketplaceDeclared':
    post:
      summary: When the merchant declared this offer source marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantOffersSourceMarketplaceDeclared'
      responses:
        204:
          description: OK
          
  '/merchantOffersSourceMarketplaceUndeclared':
    post:
      summary: When the merchant undeclared this offer source marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantOffersSourceMarketplaceUndeclared'
      responses:
        204:
          description: OK
          
  '/marketplaceMerchantCodeConfigured':
    post:
      summary: When the marketplaceMerchantCode is configured
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/marketplaceMerchantCodeConfigured'
      responses:
        204:
          description: OK
      
definitions: {}