swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN - Merchant Marketplace Exported Offer Projector CosmosDb'

host: IMN.Offer.EXP.PROJ.CosmosDb
basePath: /ExportedOfferProjectionCosmosDb

x-beezup-ops:
  codeGenType: eventHandlerActor
  repo: IMN
  appRoot: IMN.Offer.EXP.PROJ.CosmosDb
  apiName: ExportedOfferProjectionCosmosDb
  namespace: IMN.Offer.EXP.PROJ.CosmosDb
  comment: |
    Actor
  using:
  - IMN.Offer.Schemas

paths:

  '/merchantMarketplaceOfferCreated':
    post:
      summary: merchant offers exported for a marketplace 
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantMarketplaceOfferCreated'
      responses:
        204:
          description: OK

  '/merchantMarketplaceOfferUpdated':
    post:
      summary: merchant offers exported for a marketplace 
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantMarketplaceOfferUpdated'
      responses:
        204:
          description: OK

  '/merchantMarketplaceOfferDeleted':
    post:
      summary: merchant offers exported for a marketplace 
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantMarketplaceOfferDeleted'
      responses:
        204:
          description: OK

definitions: {}