swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN CORE - Merchant Actor'


basePath: /MerchantActor
x-IMN-api-ops:
  codeGenType: actor
  repo: IMN
  product: IMN-CORE
  group: merchant
  appRoot: IMN.MER.Actors
  apiName: MerchantActor
  namespace: IMN.MER.Actors
  applicationShortName: MER.Actors
  comment: |
    Actor - Test server side generation script t26
  using:
  - IMN.MER.Commands
  - IMN.MER.Events
  - IMN.MER.Schemas
  


paths:

  '/createMerchant':
    post:
      summary: When the merchant creates his account on IMN
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/createMerchant'
      responses:
        204:
          description: OK
        409:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantCodeAlreadyUsed'
  '/updateMerchantAcountInfo':
    post:
      summary: When the merchant updates his account information
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/updateMerchantAcountInfo'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
          
  '/declareSourceMarketplace':
    post:
      summary: When the merchant wants to declare source marketplace by using his credential
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/declareMerchantOffersSourceMarketplace'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'

  '/undeclareSourceMarketplace':
    post:
      summary: When the merchant wants to declare source marketplace by using his credential
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/undeclareMerchantOffersSourceMarketplace'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
        412:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/notOfferSourceMarketplace'
          
  '/configureMarketplaceApiCredential':
    post:
      summary: When the merchant configure a api credential for a marketplace
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/configureMerchantMarketplaceCredential'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
        403:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMarketplaceCredential'

  '/externalMerchantMarketplaceSubscriptionsRequested':
    post:
      summary: When the registration process has been completed
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/externalMerchantMarketplaceSubscriptionsRequested'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'

  '/refuseMerchantMarketplaceSubscription':
    post:
      summary: When the marketplace refuses the merchant subscription
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/refuseMerchantMarketplaceSubscription'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
          
  '/blockMerchantMarketplaceSubscription':
    post:
      summary: When the marketplace blocks the merchant subscription
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/blockMerchantMarketplaceSubscription'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
          
  '/acceptMerchantMarketplaceSubscription':
    post:
      summary: When the marketplace accepts the merchant subscription
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/acceptMerchantMarketplaceSubscription'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'

  '/enableMarketplace':
    post:
      summary: When the merchant wants to enable offer publication & order managementon a marketplace
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/enableMerchantMarketplace'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'


  '/disableMarketplace':
    post:
      summary: When the merchant wants to disable offer publication & order management on a marketplace
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/disableMerchantMarketplace'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'


  '/reenableOrderImportation':
    post:
      summary: When the merchant wants to reenable order importation on a marketplace
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/reenableMerchantMarketplaceOrderImportation'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
  
  
  '/disableOrderImportation':
    post:
      summary: When the merchant wants to disable order importation on a marketplace
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/disableMerchantMarketplaceOrderImportation'
      responses:
        204:
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
          
  '/configureMerchantMarketplacePricingSetting':
    post:
      summary: When the merchant wants to configure the price rule for a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/configureMarketplacePricingSetting'
      responses:
        204: 
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
          

  '/configureMerchantMarketplaceShippingSettings':
    post:
      summary: When the merchant wants to configure the shipping settings a marketplace
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/configureMarketplaceShippingSettings'
      responses:
        204: 
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'
          
  '/configureMarketplaceMerchantCode':
    post:
      summary: When a marketplace wants to configure a merchant MarketplaceMerchantCode  
      parameters:
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-commands/1.0#/definitions/configureMarketplaceMerchantCode'
      responses:
        204: 
          description: OK
        404:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/merchantOrMarketplaceNotFound'
        400:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/invalidMerchantCode'         
  '/credentialExpired':
    post:
      summary: Scheduled message to check if the merchant marketplace api credential is expired
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceCredentialExpired'
      responses:
        204:
          description: OK

definitions: {}