swagger: '2.0'
info:
  title: Merchant API - List of Values
  description: This API gives you access to list of values.
  version: "1.0"
  contact:
    email: support@beezup.com
    
 
  license:
    name: IMN 
    url: https://go.imn.io
  
  x-changeComment: |
    No change. Server side regeneration.


 
host: api.imn.io
basePath: /merchant/lov/v1

x-basePath: /merchant/lov/v1

schemes:
  - https



consumes:
  - application/json
produces:
  - application/json


tags:
- name: LOV
  description: All LOV operations


paths:
  /:
    get:
      summary: Get all list names
      operationId: GetUserLovIndex
      tags:
      - LOV
      responses:
        '200':
          description: Get the list names
          headers:
            ETag:
              description: The ETag corresponding to the LOV Index
              type: string
            Cache-Control:
              description: |
                Indicates the directive around the caching mechanisms.\
                For more information, please go to this link: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9
              type: array
              collectionFormat: csv
              items:
                type: string
          schema:
            $ref: '#/definitions/userLovIndex'
        304:
          description: The ETag sent in the http header If-None-Match did not change. So you can keep your version.
          headers:
            ETag:
              description: The ETag corresponding to the LOV Index
              type: string
              
            Cache-Control:
              description: |
                Indicates the directive around the caching mechanisms.\
                For more information, please go to this link: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9
              type: array
              collectionFormat: csv
              items:
                type: string
          
        default:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/GeneralError'
            

  '/{listName}':
    get:
      tags:
      - LOV
      summary: Get the list of values related to this list name
      operationId: GetUserListOfValues
      parameters:
        - name: listName
          in: path
          required: true
          description: The list of value name your want to get
          type: string 
        - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/parameters/acceptLanguageParameter'
        - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/parameters/ifNoneMatchParameter'
      responses:
        '200':
          description: The list of values
          headers:
            ETag:
              description: The ETag corresponding to the LOV Index
              type: string
              
            Cache-Control:
              description: |
                Indicates the directive around the caching mechanisms.\
                For more information, please go to this link: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9
              type: array
              collectionFormat: csv
              items:
                type: string
            Content-Language:
              description: Indicates the language use in the response
              type: array
              collectionFormat: csv
              items:
                type: string
              
              
          schema:
            $ref: '#/definitions/userListOfValuesResponse'
        304:
          description: The ETag sent in the http header If-None-Match did not change. So you can keep your version.
          headers:
            ETag:
              description: The ETag corresponding to the LOV Index
              type: string
              
            Cache-Control:
              description: |
                Indicates the directive around the caching mechanisms.\
                For more information, please go to this link: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9
              type: array
              collectionFormat: csv
              items:
                type: string

        404:
          description: List not found
          schema:
            $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/errorResponseMessage'
        default:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/responses/GeneralError'




definitions:

  userLovIndex:
    type: object
    properties:
      links:
        $ref: '#/definitions/userLovIndexLinks'
        
  userLovIndexLinks:
    type: object
    properties:
      self:
        $ref: '#/definitions/links.GetUserLovIndexLink'

      lists:
        $ref: '#/definitions/userLovLinks'


    

  userLovLinks:
    description: List of lov link. The key is the list name.
    type: object
    additionalProperties:
      $ref: '#/definitions/links.GetUserListOfValuesLink'


  links.GetUserListOfValuesLink:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/link3'
    - example:
        href: /merchant/lov/v1/Go2CultureName
        method: GET

  
  links.GetUserLovIndexLink:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/link3'
    - example:
        href: /merchant/lov/v1
        method: GET
        




  userListOfValuesResponse:
    type: object
    properties:
      links:
        $ref: '#/definitions/userListOfValuesResponseLinks'
# [Style Validator (0015615c-61c2-47a4-b7b1-da373f4df0ef) : All model properties must have examples]: Field 'example' required in 'properties'
# [Style Validator (d34d4816-d4b3-41fd-92a9-4ce2f969f3c5) : All model properties must have examples]: Field 'example' required in 'properties'
      items:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/listOfValueItem'
        
            
        
  
  userListOfValuesResponseLinks:
    type: object
    properties:
      self:
        $ref: '#/definitions/links.GetUserListOfValuesLink'
    

x-azure-api-id: 'MerchantLovV1'