swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN - Merchant Marketplace Offer Message Pusher'

host: IMN.Offer.EXP.Pusher
basePath: /ExportedOfferMessagePusher

x-beezup-ops:
  codeGenType: eventHandlerActor
  repo: IMN
  product: IMN-CORE
  group: offer
  appRoot: IMN.Offer.EXP.Pusher
  apiName: ExportedOfferMessagePusher
  namespace: IMN.Offer.EXP.Pusher
  applicationShortName: Offer.EXP.Pusher
  comment: |
    Actor
  using:
  - IMN.Offer.Events
  - IMN.Offer.EXP.Events
  references:
  - IMN.Offer.Events
  - IMN.Offer.EXP.Events
  

tags: 
- name: Offer Exportation Events
- name: Merchant Offer Events 

paths:


  '/offerExportPartitionInitializationCompleted':
    post:
      tags: 
      - Offer Exportation Events
      summary: When the offer publication is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-events/1.0#/definitions/offerExportPartitionInitializationCompleted'
      responses:
        204:
          description: OK

  '/offerExportPartitionInitializationStarted':
    post:
      tags: 
      - Offer Exportation Events
      summary: When the initializer starts to retrieve merchant offers. Propagated from initializer to purge the transformed offers referential
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-events/1.0#/definitions/offerExportPartitionInitializationStarted'
      responses:
        204:
          description: OK




  '/merchantOfferUnpublished':
    post:
      tags: 
      - Merchant Offer Events
      summary: When the offer is unpublished
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferUnpublished'
      responses:
        204:
          description: OK
          
  '/merchantOfferReceived':
    post:
      tags: 
      - Merchant Offer Events
      summary: When the merchant offer is Received
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferReceived'
      responses:
        204:
          description: OK


  '/merchantOfferDeleted':
    post:
      tags: 
      - Merchant Offer Events
      summary: When the merchant offer is deleted
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferDeleted'
      responses:
        204:
          description: OK


      
definitions: {}